### PR TITLE
SciFi: TT and HPT

### PR DESCRIPTION
**Pull request by aleksanp**
First version of scintillating fibre tracker in Target Tracker (23 planes) and High Precision Tracker (5 planes); Values emulsion (BrZ=7.6 cm) and CES (CESW=3.5 cm) are set manually.

### CODE REVIEW

**Comment by olantwin** [comment]
Hi,

Looking good, but two small comments:

* In some cases you commented the old lines instead of just modifying them. We have git to keep track of what changed, so you can just remove the old lines
* What does the `python/shipTargetTracker.py` script do? Looking at the filename of the ROOT file loaded it will only work on a particular system. If it's not for general use, I would remove it from the pull request.

Cheers,
Oliver

**Comment by ThomasRuf** [comment]
Question 1: Are these changes compatible with reading already simulated data? 
Question 2: Can you confirm that there are no overlaps produced by the changes in the geometry?

**Comment by aleksanp** [comment]
1) My part includes only inserting the volumes (TT and HPT, which has the same construction as TT) and methods for setting of parameters (sizes). I am not sure about emulsion, so I can remove all parts connected with emulsion (here I set the Emulsion and CES sizes manually, but it is temporary). Reading and digitazing of simulated data will be in additional script which I am working on.

**Comment by aleksanp** [comment]
2) I am not sure how to do it correctly. I checked that manually using "getGeoInformation.py" with scifi volumes (vislvl = 7 in fMan.Init()). What can you advise?

**Comment by ThomasRuf** [comment]
1.) with the actual version of FairShip in GIT do the following, 
A) simulate some events, run reconstruction and analysis:
python $FAIRSHIP/macro/run_simScript.py
>> Macro finished succesfully.
>> Output file is  ship.conical.Pythia8-TGeant4.root

python $FAIRSHIP/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root

python -i $FAIRSHIP/macro/ShipAna.py -f ship.conical.Pythia8-TGeant4_rec.root -g geofile_full.conical.Pythia8-TGeant4.root


B) move to your new compiled version of FairShip and run analysis and reco of previous produced data:

python -i $FAIRSHIP/macro/ShipAna.py -f ship.conical.Pythia8-TGeant4_rec.root -g geofile_full.conical.Pythia8-TGeant4.root

python $FAIRSHIP/macro/ShipReco.py -f ship.conical.Pythia8-TGeant4.root -g geofile_full.conical.Pythia8-TGeant4.root

if these runs without errors, your changes are backwards compatible.


2) For the overlap checking, run_simScript.py, change line 11, debug = 0 to debug = 2, and run it.

**Comment by ThomasRuf** [comment]
May I ask about the status of this pull request?

**Comment by aleksanp** [comment]
Overlaps were fixed and checked following the instruction, but next there are problems after upgrading my local Linux system to 18.10 (because ShipAna and ShipReco didn't work). So now I am trying to fix FairShip. If it would not work I'll try with lxplus (I have not used that before)

**Comment by ThomasRuf** [comment]
What problems? With current version of FairShip, I am happily running on 18.04.

**Comment by aleksanp** [comment]
1) The problem with Python-modules was fixed by changing "terminal.py" (right during the compilation because it renews each time) : 
`from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size`
to 
`from shutil_backports import get_terminal_size as _get_terminal_size`
2) For XRootD@v4.8.3 I had to remove from the system cmake
3) XercesC can be fixed in two way: a) adding prefix `--disable-dependency-tracking` in the recipe
b) using version with cmake instead automake (but first need to install cmake and remove later) 
4) FairRoot had some trouble in 99% of compilation. It was resolved by setting `-DBUILD_EXAMPLES=OFF` in the FairRoot recipe. 
5) FairRoot uses a header "FairGeoPassivePar.h" from the examples. So I had to move a copy in `$FAIRROOT_ROOT/include from "_/sw/SOURCES/FairRoot/........./examples/common/passive/FairGeoPassivePar.h"`

**Comment by aleksanp** [comment]
So, it runs now successfully (thanks to Oliver and Antonio), but with the ShipReco.py the same problem happens even after upgrading to ubuntu 18.10. It seems there is a problem with numpy/scipy.

**Comment by ThomasRuf** [comment]
what is terminal.py? And where is it used?

I have not observed any issues with XRootD and XercesC when building in Ubuntu / SLC6 or 7. 

If you set examples off for FairRoot, you are ignoring some underlying problem. Why does making examples fail?

**Comment by aleksanp** [comment]
~/SHiPBuild/sw/INSTALLROOT/978a2b617f623a3a0ba0b8b37cf6b62236434e67/ubuntu1810_x86-64/Python-modules/1.0-1/lib/python2.7/site-packages/IPython/utils/terminal.py":

**Comment by ThomasRuf** [comment]
regarding your modifications, we don't want to have in python/shipDet_conf.py

 exclusionList = ["Muon","Ecal","Hcal","Strawtubes","Veto","Magnet","MuonShield","TargetStation","TimeDet"] 

this will anyhow cause problems for ShipReco and ShipAna. 

It would be good if you can remove changes which you made for your private tests.
things like adding or removing a blank, 0 -> 0. , it just confuses what are the real changes.

**Comment by aleksanp** [comment]
Sure, sorry! I forgot about that!

**Comment by ThomasRuf** [comment]
python module: This is a Ubuntu 18.10 issue? It would require to modify shipdist/python-modules.sh and discuss with the alibuild people.

**Comment by ThomasRuf** [comment]
Does the problem with ShipReco.py occurs with or without the above exclusion list?

**Comment by olantwin** [comment]
> python module: This is a Ubuntu 18.10 issue? It would require to modify shipdist/python-modules.sh and discuss with the alibuild people.

I can try looking into the python modules issue. Since out version of python-modules.sh is very different from the Alice one, we're probably on our own.

**Comment by aleksanp** [comment]
> Does the problem with ShipReco.py occurs with or without the above exclusion list?
That problem occurs even in ShipSoft-master branch where there are not my changes

**Comment by aleksanp** [comment]
Ok! The problem with numpy/scipy are resolved. As I suppose it could be incorrect connection of different versions of Python on pc (newest) and Python-module (old) from alibuild

So now all three scripts run_simScript, ShipReco and ShipAna successfully work with my branch

What is needed to show?

**Comment by antonioiuliano2** [comment]
Hi, first thank you for all your hard work.

I would be cautious, however, to upgrade the default visualization level of the Event Display from 4 to 7. When all the volumes are rendered, it becomes so slow that it becomes unmanageable.

Best regards,
Antonio

**Comment by antonioiuliano2** [comment]
> Ok! The problem with numpy/scipy are resolved. As I suppose it could be incorrect connection of different versions of Python on pc (newest) and Python-module (old) from alibuild
> 
> So now all three scripts run_simScript, ShipReco and ShipAna successfully work with my branch
> 
> What is needed to show?

Did you try to apply ShipReco to a simulation from the master branch, in order to test backward compatibility?
Because, when i have tried to do it myself, I have seen this error:

Traceback (most recent call last):
  File "/home/antonio/SHIPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/macro/ShipReco.py", line 132, in <module>
    modules = shipDet_conf.configure(run,ShipGeo)
  File "/home/antonio/SHIPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/python/shipDet_conf.py", line 251, in configure
    NuTauTarget.SetTargetWallDimension(ship_geo.NuTauTarget.WallXDim, ship_geo.NuTauTarget.WallYDim, ship_geo.NuTauTarget.WallZDim)
AttributeError: 'AttrDict' object has no attribute 'WallXDim'

**Comment by aleksanp** [comment]
> Hi, first thank you for all your hard work.
> 
> I would be cautious, however, to upgrade the default visualization level of the Event Display from 4 to 7. When all the volumes are rendered, it becomes so slow that it becomes unmanageable.
> 
> Best regards,
> Antonio

Ok! I will change back to 4 level

**Comment by aleksanp** [comment]
> > Ok! The problem with numpy/scipy are resolved. As I suppose it could be incorrect connection of different versions of Python on pc (newest) and Python-module (old) from alibuild
> > So now all three scripts run_simScript, ShipReco and ShipAna successfully work with my branch
> > What is needed to show?
> 
> Did you try to apply ShipReco to a simulation from the master branch, in order to test backward compatibility?
> Because, when i have tried to do it myself, I have seen this error:
> 
> Traceback (most recent call last):
> File "/home/antonio/SHIPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/macro/ShipReco.py", line 132, in
> modules = shipDet_conf.configure(run,ShipGeo)
> File "/home/antonio/SHIPBuild/sw/ubuntu1710_x86-64/FairShip/master-1/python/shipDet_conf.py", line 251, in configure
> NuTauTarget.SetTargetWallDimension(ship_geo.NuTauTarget.WallXDim, ship_geo.NuTauTarget.WallYDim, ship_geo.NuTauTarget.WallZDim)
> AttributeError: 'AttrDict' object has no attribute 'WallXDim'

You are right! Sorry! 
I did the last time  `run_simScript.py -> ShipReco -> ShipAna` so everything was worked on my branch.

**Comment by antonioiuliano2** [comment]
Hello again,

could you please change the name of the new attributes from n_films to n_plates? Passive plates in a ECC brick are 56, while the number of emulsions films is one more, since the bricks starts and ends with emulsions. Sorry, I have noticed that a comment in Target.cxx is wrong and it has probably confused you.

This is a minor change, but since the pull request has not yet been completed, it is better to fix it now, since it becomes troublesome to change names later.

Best regards,
Antonio

**Comment by aleksanp** [comment]
Ok, sure! I agree with you

**Comment by ThomasRuf** [comment]
this commit has now a conflict, nutaudet/Target.cxx

**Comment by ThomasRuf** [comment]
Any progress here? What should be done with this pull request?

thomas

**Comment by aleksanp** [comment]
Now the branch is able to merge with Fairship/master

**Comment by ThomasRuf** [comment]
After merging, I noticed the following error:
...
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
[ERROR] TGeoManager::CloseGeometry() modified the volume list from 1287 to 1289
This almost certainly means inconsistent lookup structures used in simulation/stepping.

Could somebody please investigate this and fix it asap, otherwise we have to revert to before the merge.

**Comment by ThomasRuf** [comment]
One more information:
The error disappears when removing HighPrecisionTrackers from the list of detectors to build.

**Comment by ThomasRuf** [comment]
By the way, did anybody ever run an overlap check? I see hundreds of overlaps:
 = Overlap ov00010: volMagRegion/volTarget_1/Wall_11/Row_6/Cell_6/CES_1/RohacellGap_0 overlapping volMagRegion/volDT_4000 ovlp=1.16499
 = Overlap ov00011: volMagRegion/volTarget_1/Wall_11/Row_1/Cell_1/CES_1/RohacellGap_0 overlapping volMagRegion/volDT_4000 ovlp=1.16499
...
 = Overlap ov00119: volMagRegion/volTarget_1/Wall_3/Row_2/Cell_5/CES_1/RohacellGap_1 overlapping volMagRegion/volDT_2000 ovlp=1.16075
 = Overlap ov00120: volMagRegion/volTarget_1/Wall_3/Row_2/Cell_4/CES_1/EmulsionCES_2 overlapping volMagRegion/volDT_2000 ovlp=1.16075
...

The geoManager will not be able to locate in which volume/node it is, and the transport of particles will be wrong! This needs to be fixed urgently.

**Comment by antonioiuliano2** [comment]
Thank to Alexander's suggestions, I have done a first fix, it was a problem with the assembly volumes, since the geometry cannot get DX, DY, and DZ. I have done a first fix here: #289 

However, there are still strange overlaps within other parts of the geometry:
=== Overlaps for FAIRGeom ===
 = Overlap ov00000: cave/floorM_1 overlapping cave/DecayVolume_1/floor1_0 ovlp=210
 = Overlap ov00001: cave/MagVolume_1/T3_1/LongOutCover_Y2_1 overlapping cave/Tr3_3 ovlp=19.9978
 = Overlap ov00002: cave/SHiPMagnet_1/CV_4 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7.1
 = Overlap ov00003: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_1 ovlp=7
 = Overlap ov00004: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_1 ovlp=7
 = Overlap ov00005: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7
 = Overlap ov00006: cave/SHiPMagnet_1/MCoil4_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7
 = Overlap ov00007: cave/MagVolume_1/T3_1/VertMagCover_y_1 overlapping cave/Ecal_1 ovlp=2.32995
 = Overlap ov00008: cave/MagVolume_1/T3_1/VertMagCover_X_15 overlapping cave/Ecal_1 ovlp=2.32995
 = Overlap ov00009: cave/MagVolume_1/T3_1/VertMagCover_X_14 overlapping cave/Ecal_1 ovlp=2.32995
 = Overlap ov00010: cave/DecayVolume_1/T2_1/VetoInnerWall_0/VetoInnerWall_block3_0 overlapping cave/MagVolume_1/T3_1/VertMagCover_X_17 ovlp=1.11394
 = Overlap ov00011: cave/DecayVolume_1/T2_1/VetoInnerWall_0/VetoInnerWall_block3_0 overlapping cave/MagVolume_1/T3_1/VertMagCover_X_16 ovlp=1.11394
 = Overlap ov00012: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_2 ovlp=0.365493
 = Overlap ov00013: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_3 ovlp=0.365493
 = Overlap ov00014: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_3 ovlp=0.365493
 = Overlap ov00015: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_4 ovlp=0.365493
 = Overlap ov00016: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_2 ovlp=0.125083
 = Overlap ov00017: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_4 ovlp=0.125083
 = Overlap ov00018: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_2 ovlp=0.125083
 = Overlap ov00019: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_3 ovlp=0.125083
 = Overlap ov00020: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_4 ovlp=0.125083
Info in <TGeoNodeMatrix::CheckOverlaps>: Checking overlaps for TargetArea and daughters within 0.0001


I do not know what the cause could be, but it does not seem related to the nutaudet code. What do you think about it?
Best regards,
Antonio

**Comment by ThomasRuf** [comment]
Ievgen is working on the other overlaps. Cheers, Thomas

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>




On Sat, Sep 21, 2019 at 2:28 PM +0200, "Antonio" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank to Alexander's suggestions, I have done a first fix, it was a problem with the assembly volumes, since the geometry cannot get DX, DY, and DZ. I have done a first fix here: #289<https://github.com/ShipSoft/FairShip/pull/289>

However, there are still strange overlaps within other parts of the geometry:
=== Overlaps for FAIRGeom ===
= Overlap ov00000: cave/floorM_1 overlapping cave/DecayVolume_1/floor1_0 ovlp=210
= Overlap ov00001: cave/MagVolume_1/T3_1/LongOutCover_Y2_1 overlapping cave/Tr3_3 ovlp=19.9978
= Overlap ov00002: cave/SHiPMagnet_1/CV_4 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7.1
= Overlap ov00003: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_1 ovlp=7
= Overlap ov00004: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_1 ovlp=7
= Overlap ov00005: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7
= Overlap ov00006: cave/SHiPMagnet_1/MCoil4_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_1 ovlp=7
= Overlap ov00007: cave/MagVolume_1/T3_1/VertMagCover_y_1 overlapping cave/Ecal_1 ovlp=2.32995
= Overlap ov00008: cave/MagVolume_1/T3_1/VertMagCover_X_15 overlapping cave/Ecal_1 ovlp=2.32995
= Overlap ov00009: cave/MagVolume_1/T3_1/VertMagCover_X_14 overlapping cave/Ecal_1 ovlp=2.32995
= Overlap ov00010: cave/DecayVolume_1/T2_1/VetoInnerWall_0/VetoInnerWall_block3_0 overlapping cave/MagVolume_1/T3_1/VertMagCover_X_17 ovlp=1.11394
= Overlap ov00011: cave/DecayVolume_1/T2_1/VetoInnerWall_0/VetoInnerWall_block3_0 overlapping cave/MagVolume_1/T3_1/VertMagCover_X_16 ovlp=1.11394
= Overlap ov00012: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_2 ovlp=0.365493
= Overlap ov00013: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_3 ovlp=0.365493
= Overlap ov00014: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_3 ovlp=0.365493
= Overlap ov00015: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_X1_4 ovlp=0.365493
= Overlap ov00016: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_2 ovlp=0.125083
= Overlap ov00017: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_4 ovlp=0.125083
= Overlap ov00018: cave/SHiPMagnet_1/MCoil3_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_2 ovlp=0.125083
= Overlap ov00019: cave/SHiPMagnet_1/MCoil2_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_3 ovlp=0.125083
= Overlap ov00020: cave/SHiPMagnet_1/MCoil1_1 overlapping cave/MagVolume_1/T3_1/LongOutCover_Y1_4 ovlp=0.125083
Info in TGeoNodeMatrix::CheckOverlaps: Checking overlaps for TargetArea and daughters within 0.0001

I do not know what the cause could be, but it does not seem related to the nutaudet code. What do you think about it?
Best regards,
Antonio
